//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "certificates")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub layer: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub block: String,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub cert: Option<Vec<u8>>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))")]
    pub valid: Vec<u8>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
