//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "poets")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub r#ref: String,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub poet: Option<Vec<u8>>,
    pub service_id: Option<String>,
    pub round_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
